# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Django Daisy Dashboard
site_url: https://hypy13-django-daisy.hf.space/en/admin
theme:
  name: material

plugins:
  - search

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Development Guide: development.md
